spring:
  application:
    name: price-service
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      
server:
  port: 8004
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost